AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TG bot Go Lambda function

Resources:

  TGBot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Timeout: 5
      Role: !Join [ "", ["arn:aws:iam::", !Ref "AWS::AccountId", ":role/keymesh-tgbot"] ]
      Events:
        Api:
          Type: Api
          Properties:
            Path: /tgbot
            Method: post
